Update mad.yml

diff --git a/.github/workflows/mad.yml b/.github/workflows/mad.yml
--- a/.github/workflows/mad.yml
+++ b/.github/workflows/mad.yml
@@ -2,12 +2,12 @@ name: Java CI/CD Pipeline to Tomcat
 
 on:
   push:
-    branches: [ main ] # Trigger on push to main branch
+    branches: [ main ]   # Trigger on push to main branch
   workflow_dispatch: 
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
 
     steps:
       # 1. Checkout code
@@ -21,6 +21,17 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
 
+      # 3. Install Maven if missing
+      - name: Ensure Maven is installed
+        run: |
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found. Installing..."
+            sudo dnf install -y maven
+          else
+            echo "Maven is already installed"
+          fi
+          mvn -version
+
       # 3. Build with Maven
       - name: Build with Maven
         run: mvn clean package -DskipTests
@@ -33,7 +44,7 @@ jobs:
           path: target/*.war
 
   deploy:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs: build
     environment: production
 
@@ -43,8 +54,8 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: myapp
-          
-       # 6. Deploy WAR via Tomcat Manager
+
+      # 6. Deploy WAR via Tomcat Manager
       - name: Deploy to Tomcat
         run: |
           WAR_FILE=$(ls *.war)
